### ISSUE TITLE
Stop audio when leaving site

### ISSUE THREAD

**Issue by andrinmeier** [flogy/gatsby-mdx-tts#15]
This is an issue based on the discussion in https://github.com/flogy/gatsby-mdx-tts/issues/2.

The playback doesn't stop when the user leaves the page. See https://github.com/flogy/gatsby-mdx-tts/issues/2#issuecomment-688480613 for more details.

**Comment by flogy** [comment]
Thank you for the pull request. I tested and merged it today.
